name: Deploy to S3

on:
  push:
    branches:
      - main  # or any other branch you want to deploy from

jobs:
  deploy:
    runs-on: self-hosted  # your EC2 GitHub Actions runner

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4  # Pulls your GitHub repo into the runner

      - name: Deploy files to S3
        run: |
          aws s3 sync . s3://gl-aryan-cloudformation-code-bucket --delete
