name: Deploy to S3

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: self-hosted  

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4 

      - name: Deploy files to S3
        run: |
          aws s3 sync . s3://gl-aryan-cloudformation-code-bucket --delete
